export const ADD_TO_CART = 'ADD_TO_CART'
export const CHANGE_STYLE = 'CHANGE_STYLE'
export const CHANGE_PRICE = 'CHANGE_PRICE'
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const IS_SELECTED = 'IS_SELECTED'
export const IS_CHECK = 'IS_CHECK'
export const CHECK_ALL = 'CHECK_ALL'
